spring.application.name=backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/fraudshield?authSource=admin

# Google Cloud Vertex AI Configuration
# Set your GCP Project ID here to enable live Vertex AI Gemini integration
gcp.project.id=project-8c4faf45-b609-47b4-9f0
gcp.region=us-central1

# Dataset Config
fraudshield.dataset.path=/Users/hemanthbalakrishnanuthalapati/.cache/kagglehub/datasets/aryan208/financial-transactions-dataset-for-fraud-detection/versions/1/financial_fraud_detection_dataset.csv
